
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxMjk0MDI1","is_bot":false,"login":"vaaniarora","name":"vaani arora"},"headRefName":"v-create-announcement-button","number":35,"title":"va - added announcements create page and basic test for it","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/35"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"r-notjoined","number":32,"title":"rk- fixed BUG: Disallow ability to navigate to unjoined commons","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/32"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"4-F-JeffreyRemoveUsers","number":30,"title":"JM - 4F - Button and Modal to Remove and Restore Users (Merge after B3, 24)","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/30"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"24-JeffreyIncrementalPitest","number":25,"title":"JM - Added Incremental Pitest Support","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/25"},{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"4-B3-JeffreyRemoveUsers","number":23,"title":"JM - Added Authorization Gatekeeping for Suspended Users and Automatic Role Interception","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/23"}]
