
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"4-F-JeffreyRemoveUsers","number":42,"title":"jm - restore 4F","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/42"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-restoreJeffreyRemoveUsers","number":41,"title":"Pc restore jeffrey remove users","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/41"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"r-date","number":40,"title":"rk - fixed the date issue, just had to change timezone","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/40"}]
