
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"7-JeffreyCommitTracking","number":14,"title":"JM - Commit Tracking Infrastructure Setup: Dockerfile, SystemInfo, pom.xml - [Backend]","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/14"},{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"cp-UIRefractor","number":13,"title":"Cp UI refractor","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-8/pull/13"}]
